name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      acme-db:
        image: postgres
        ports:
          - 5435:5432 # Host:Container
        env:
          POSTGRES_DB: acme
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Install dependencies and playwright binaries
      - name: Install dependencies and playwright binaries
        run: |
          bun install
          bunx playwright install chromium

      - name: Setup environment variables
        run: |
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.local
          echo "POSTGRES_URL=${{ vars.POSTGRES_URL}}" >> .env.local
          echo "AUTH_URL=${{ vars.AUTH_URL}}" >> .env.local

      # Push schema to database
      - name: Push schema to database
        run: bun run ./scripts/seed.ts

      # Run Application (optional, if needed for tests)
      - name: Run Application
        run: bun run dev & sleep 10

      # Run Playwright tests
      - name: Run Playwright tests
        run: bunx playwright test
