name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5435
      POSTGRES_DB: acme
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: 'postgresql://admin:password@localhost:5435/acme'
      AUTH_SECRET: 'PDHygEY6FY4El+blZ4p9LIWiV/dw21ucS9QKf7EykxE='
      AUTH_URL: 'http://localhost:3000/'
    services:
      acme-db:
        image: postgres
        ports:
          - 5435:5432 # Host:Container
        env:
          POSTGRES_DB: acme
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Setup environment variables
        run: |
          echo "NEXTAUTH_SECRET=${{ env.AUTH_SECRET }}" >> .env.local
          echo "POSTGRES_URL=${{ env.POSTGRES_URL }}" >> .env.local
          echo "AUTH_URL=${{ env.AUTH_URL }}" >> .env.local

      - name: seed database
        run: bun run ./scripts/seed.ts
      - name: build
        run: pnpm exec next build
      - name: start
        run: pnpm exec next start & sleep 20
      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
